### ISSUE TITLE
Normalize.css VS Reset CSS

### ISSUE THREAD

**Issue by JuanjoTorres** [kaleido-css/kaleido-css#1]
Sobre lo que me comentaste del archivo **Normalize.css**:

> _El Normalize no toca todos los aspectos de los componentes, por ejemplo al botón no le quita el borde._

Existen dos tipos de archivos que se parecen bastante y hacen casi el mismo trabajo:

- _Normalize.css_

- Los archivos _Reset CSS_

Empezando por este último, los archivos _Reset CSS_ quitan totalmente el estilo de los componentes, nosotros necesitaríamos una cosa así. No obstante, _Normalize.css_ preserva algunas propiedades por defecto; por decirlo de otro modo no "desestiliza" todo. Además de esto hay otras diferencias entre estos dos, lo puedes consultar [aquí](http://stackoverflow.com/questions/6887336/what-is-the-difference-between-normalize-css-and-reset-css).

A fin de cuentas, buscamos algo que sea sencillo, aprovechable y sobretodo: **eficiente**, por lo que Materialize.css no sería una mala opción. ¿Qué opinas al respecto @SrNemuri ? ¿Deberíamos centrarnos en hacer nuestro propio archivo **Reset CSS**? o ¿Coger algunas características de **Normalize.css**?

**Comment by SrNemuri** [comment]
Considero que lo que necesitamos se encuentra más cerca de _Reset CSS,_ pero sería conveniente llevar a cabo un análisis más exhaustivo de las funciones que aporta _Normalize CSS_, puesto que podríamos aprovechar alguna que otra característica.

**Comment by JuanjoTorres** [comment]
Yo me decanto más por _Normalize.css_ porque esto de ir borrando propiedades para luego establecer el mismo valor es poco eficiente con los _Reset CSS_. Encuentro que hace la página lenta, hablando en milisegundos. Aun así lo suyo es mirarlo.

Por cierto, nuestro archivo _Normalize.css_ es la **v3.0.2** y ya hay una **v5.0.0 estandarizada**. ¿Cogemos la última? o ¿Arrancamos con esta?

**Comment by SrNemuri** [comment]
Sí, veo bien tomar la última versión... Y bueno, si consideras que ralentizará demasiado la página hacer un reset general, podemos centrarnos en resetear manualmente lo que penemos que no mola.

**Comment by JuanjoTorres** [comment]
Podemos intentar eso primero y luego al hacer una _alpha_ lo bastante robusta para experimentar. Más adelante, creamos otra rama para ver los tiempos de carga. Aunque ya te he dicho que serían milisegundos, pero podríamos fardar de ello. "Lo mas rápido y eficiente".

Lo digo también porque en la empresa toqué cosas así y me entraba escalofríos cuando utilizaba las herramientas de desarrollador de Chrome y veía todas la propiedades tachadas y vueltas añadir en otro _.class_.

Aclarado esto, cierro el _issue_.
